name: Hello GitHub Actions

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show Python Version
        run: python3 --version

      - name: Show Git Version
        run: git --version

      - name: Show Current Directory
        run: pwd

      - name: Show Files
        run: ls -la